### ISSUE TITLE
How to visualise rules in a tabular fashion and not in dendrogram format

### ISSUE THREAD

**Issue by ghost** [viadee/magie#3]
Hi, 

The output of MAGIE comes in a dendrogram text format which is difficult to interpret and analyse. Could you let me know which function I can refer to change the output format. Any hint on how to change the format will be extra helpful.

**Comment by NoItAll** [comment]
Hi,
I would disagree that the output is in the form of dendrograms: Sets of rules are displayed. One set for each label value. 

The pipelines in the validation-package extend the [AbstractStdExplanationPipeline](https://github.com/viadee/magie/blob/master/src/main/java/de/viadee/xai/framework/explanation_pipeline/AbstractStdExplanationPipeline.java). The reason for this is that this pipeline predefines several steps which are the same for all inheriting classes. Among those preconfigurations, you can see the line `new StringRuleExplanationVisualizer()`. The [StringRuleExplanationVisualizer](https://github.com/viadee/magie/blob/master/src/main/java/de/viadee/xai/framework/explanation_visualizer/StringRuleExplanationVisualizer.java) is what is used to print the sets of rules at the moment. If you replace the `StringRuleExplanationVisualizer` with another extension of `ExplanationVisualizer`, you can determine how the explanations should be visualized. In your case, you can represent them as a table. This visualized result then is the return value of the pipeline and is stored in the [GlobalExplanationContainer](https://github.com/viadee/magie/blob/master/src/main/java/de/viadee/xai/framework/explanation_pipeline/GlobalExplanationContainer.java) so that other applications can work on it.

Note that this visualization is separate from persisting the explanations as files! This is done in the [`TextExplanationPersister`](https://github.com/viadee/magie/blob/master/src/main/java/de/viadee/xai/framework/persistence/explanation_persistence_service/TextExplanationPersister.java) and should usually serve another purpose.


Please tell me if this has resolved your question :) 

Best regards

**Comment by ghost** [comment]
Thanks a lot for your reply @NoItAll . I will look into it and post if I have any queries.

**Comment by NoItAll** [comment]
I am assuming the issue is resolved :) /close
